postgres:
  image: postgres
  volumes:
    - ~/.docker-volumes/stack-twitter/db:/var/lib/postgresql/data
  expose:
    - '5432'

redis:
  image: redis
  expose:
    - "6379"

web:
  build: .
  volumes:
    - .:/app
  links:
    - postgres
    - redis
  ports:
    - "3000:3000"
  command: "foreman start"
