development: &postgres
  adapter: postgresql
  encoding: unicode
  username: postgres
  database: stacktwitter_development
  host: postgres
  pool: 5

test:
  <<: *postgres
  database: stacktwitter_test

production:
  <<: *postgres
  database: stacktwitter_production
